In [12]:

import pandas as pd

In [23]:
df = pd.read_excel(r"\\main.oecd.org\ASgenDCD\DEVELOPMENT_AID\__PROCESSING\checklist_r\2_functions\test_crstemplate_LT.xlsx",header = 1)
df = df.loc[1:].reset_index(drop=True)
df["error_message"] = ""
df["warning_message"] = ""

In [14]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [15]:

df.head()  # Display the first few rows of the DataFrame

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element,error_message,warning_message
0,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,3000,African Development Bank,12004.0,2,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
1,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,2,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
2,2024,2024-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,NaN,8,10,110,A02,Programme d'agriculture durable et de sécurité...,99810,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
3,2024,2021-12-31 00:00:00,1,1,20220000003,abcd,3,998,Institute for Advanced Research and Policy Stu...,51010.0,4,10,110,A02,Education for All: Inclusive Learning Environm...,42559;12264,"Himalayan Mountain Range, Nepal",NaN,NaN,NaN,The objective of this project is to ensure acc...,5.a;5.b,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0,2,302,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,
4,2024,2024-01-01 00:00:00,1,1,20220000004,abcd,1,998,Republic of Ireland,12003.0,8,21,420,NaN,Clean Water and Sanitation for Communities,41000,"Great Rift Valley, Kenya",NaN,NaN,NaN,This project aims to provide clean and safe dr...,5,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2,820,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,

#### errormessage : Recipient code not on DAC list of recipients

In [ ]:
# import recipients_list

#### errormessage : When recipient code = 3000, Bi/Multi should = 2

In [19]:
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            ((df["Recipient code"]== 3000) &
              (df["Bi/Multi"]!=2))]

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element,error_message,warning_message
11,2024,2022-01-15 00:00:00,1,1,20220000002,abcd,1,3000,International Committee of the Red Cross,21009.0,7,10,110,A01,Programme d'agriculture durable et de sécurité...,12240:100,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,

In [20]:
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            ((df["Recipient code"]== 3000) &
              (df["Bi/Multi"]!=2)), "error_message"] = df["error_message"] + "When recipient code = 3000, Bi/Multi should = 2"

In [21]:
df[["Type of flow (main DAC 1 category)","Recipient code", "Bi/Multi", "error_message"]].head(20)

    Type of flow (main DAC 1 category)  Recipient code  Bi/Multi                                    error_message
0                                   10            3000         2
1                                   10             998         2
2                                   10             249         8
3                                   10             998         4
4                                   21             998         8
5                                   10             998         3
6                                   10             998         3
7                                   60             998         7
8                                   10             998         2
9                                   10             249         7
10                                  10             249         7
11                                  10            3000         7  When recipient code = 3000, Bi/Multi should = 2
12                                  10             998         8
13                                  10             998         2
14                                  10             998         2

#### errormessage : In-donor refugee costs cannot be attributed to a specific recipient and therefore should be marked 998;

In [24]:
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            (df["Co-operation modality (replaces the type of aid)"].astype(str).str.startswith("H0")) & 
            (df["Co-operation modality (replaces the type of aid)"]!= "H01") &
              (df["Recipient code"]!= 998)]

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element,error_message,warning_message
17,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,85,African Development Bank,12004.0,1,10,420,H06,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,

In [25]:
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            (df["Co-operation modality (replaces the type of aid)"].astype(str).str.startswith("H0")) & 
            (df["Co-operation modality (replaces the type of aid)"]!= "H01") &
              (df["Recipient code"]!= 998), "error_message"] = df["error_message"] + " ;In-donor refugee costs cannot be attributed to a specific recipient and therefore should be marked 998; "

In [26]:
df[["Type of flow (main DAC 1 category)","Recipient code", "Bi/Multi","Co-operation modality (replaces the type of aid)", "error_message"]].head(20)

    Type of flow (main DAC 1 category)  Recipient code  Bi/Multi Co-operation modality (replaces the type of aid)                                      error_message
0                                   10            3000         2                                              NaN
1                                   10             998         2                                              NaN
2                                   10             249         8                                              A02
3                                   10             998         4                                              A02
4                                   21             998         8                                              NaN
5                                   10             998         3                                              B01
6                                   10             998         3                                              B01
7                                   60             998         7                                              NaN
8                                   10             998         2                                              B01
9                                   10             249         7                                              B01
10                                  10             249         7                                              A01
11                                  10            3000         7                                              A01
12                                  10             998         8                                              B02
13                                  10             998         2                                              B02
14                                  10             998         2                                              NaN
15                                  10             998         1                                              H02
16                                  10              85         1                                              H01
17                                  10              85         1                                              H06   ;In-donor refugee costs cannot be attributed ...