In [43]:

import pandas as pd
import pyreadr

In [56]:
df = pd.read_excel(r"\\main.oecd.org\ASgenDCD\DEVELOPMENT_AID\__PROCESSING\checklist_r\2_functions\test_crstemplate_LT.xlsx",header = 1)
#df_recipients_list = pd.read_csv(r"\\main.oecd.org\ASgenDCD\DEVELOPMENT_AID\__PROCESSING\checklist_r\2_functions\dcd_vdaclistofodarecipients_20250924_110837.csv")
#df_regional_recipients_list = pd.read_csv(r"\\main.oecd.org\ASgenDCD\DEVELOPMENT_AID\__PROCESSING\checklist_r\2_functions\DCD_vRecipientGroup_20250924_112202.csv")

df_lookup = pyreadr.read_r(r"\\main.oecd.org\ASgenDCD\DEVELOPMENT_AID\__PROCESSING\checklist_r\3_share\lookups_checklist.RData")
df = df.loc[1:].reset_index(drop=True)
df["error_message"] = ""
df["warning_message"] = ""

In [57]:
df_lookup

OrderedDict([('annex2_lookup',
                   annex2_lookup
              0            30010
              1            41101
              2            41102
              3            41103
              4            41104
              5            41105
              6            41106
              7            41107
              8            41108
              9            41110
              10           41111
              11           41112
              12           41114
              13           41116
              14           41119
              15           41120
              16           41121
              17           41122
              18           41123
              19           41125
              20           41126
              21           41127
              22           41128
              23           41129
              24           41130
              25           41131
              26           41134
              27           41135
              28           41140
              29           41141
              30           41143
              31           41144
              32           41145
              33           41146
              34           41147
              35           41149
              36           41150
              37           41151
              38           41301
              39           41302
              40           41303
              41           41304
              42           41305
              43           41306
              44           41307
              45           41308
              46           41309
              47           41310
              48           41312
              49           41313
              50           41314
              51           41315
              52           41316
              53           41317
              54           41319
              55           41320
              56           41321
              57           41402
              58           41403
              59           42001
              60           42003
              61           42004
              62           43001
              63           43002
              64           43003
              65           43005
              66           43006
              67           43007
              68           44001
              69           44002
              70           44003
              71           44004
              72           44005
              73           44006
              74           44007
              75           44008
              76           45001
              77           45002
              78           45003
              79           46002
              80           46003
              81           46004
              82           46005
              83           46006
              84           46007
              85           46008
              86           46009
              87           46012
              88           46013
              89           46015
              90           46016
              91           46017
              92           46018
              93           46019
              94           46020
              95           46021
              96           46022
              97           46023
              98           46024
              99           46025
              100          46026
              101          46027
              102          47001
              103          47002
              104          47003
              105          47005
              106          47009
              107          47011
              108          47013
              109          47015
              110          47019
              111          47022
              112          47025
              113          47026
              114          47027
              115          47029
              116          47034
              117          47036
              118          47037
              119          47040
              120          47044
              121          47045
              122          47046
              123          47050
              124          47058
              125          47059
              126          47061
              127          47064
              128          47066
              129          47067
              130          47068
              131          47073
              132          47074
              133          47076
              134          47077
              135          47078
              136          47079
              137          47080
              138          47081
              139          47082
              140          47083
              141          47084
              142          47086
              143          47087
              144          47089
              145          47092
              146          47093
              147          47095
              148          47096
              149          47097
              150          47098
              151          47100
              152          47105
              153          47106
              154          47107
              155          47109
              156          47110
              157          47111
              158          47113
              159          47114
              160          47116
              161          47117
              162          47118
              163          47119
              164          47120
              165          47121
              166          47122
              167          47123
              168          47124
              169          47125
              170          47127
              171          47128
              172          47129
              173          47130
              174          47131
              175          47132
              176          47134
              177          47135
              178          47136
              179          47137
              180          47138
              181          47140
              182          47141
              183          47142
              184          47143
              185          47144
              186          47145
              187          47146
              188          47147
              189          47148
              190          47149
              191          47150),
             ('channels_list',
                   channels_list
              0          11001.0
              1          11002.0
              2          11003.0
              3          11004.0
              4          12001.0
              5          12002.0
              6          12003.0
              7          12004.0
              8          21001.0
              9          21002.0
              10         21003.0
              11         21004.0
              12         21005.0
              13         21006.0
              14         21007.0
              15         21008.0
              16         21009.0
              17         21010.0
              18         21011.0
              19         21013.0
              20         21014.0
              21         21015.0
              22         21016.0
              23         21017.0
              24         21018.0
              25         21019.0
              26         21020.0
              27         21021.0
              28         21022.0
              29         21023.0
              30         21024.0
              31         21025.0
              32         21026.0
              33         21027.0
              34         21028.0
              35         21029.0
              36         21030.0
              37         21031.0
              38         21032.0
              39         21033.0
              40         21034.0
              41         21035.0
              42         21036.0
              43         21037.0
              44         21038.0
              45         21039.0
              46         21040.0
              47         21041.0
              48         21042.0
              49         21043.0
              50         21044.0
              51         21045.0
              52         21046.0
              53         21047.0
              54         21048.0
              55         21049.0
              56         21050.0
              57         21051.0
              58         21053.0
              59         21054.0
              60         21055.0
              61         21056.0
              62         21057.0
              63         21058.0
              64         21059.0
              65         21060.0
              66         21061.0
              67         21062.0
              68         21063.0
              69         21064.0
              70         21501.0
              71         21502.0
              72         21503.0
              73         21504.0
              74         21505.0
              75         21506.0
              76         21507.0
              77         21508.0
              78         21509.0
              79         22501.0
              80         22502.0
              81         23501.0
              82         30001.0
              83         30003.0
              84         30004.0
              85         30005.0
              86         30006.0
              87         30007.0
              88         30008.0
              89         30009.0
              90         30010.0
              91         30011.0
              92         30012.0
              93         30013.0
              94         30014.0
              95         30015.0
              96         30016.0
              97         30017.0
              98         30018.0
              99         30019.0
              100        30020.0
              101        31001.0
              102        31002.0
              103        31003.0
              104        31004.0
              105        31005.0
              106        31006.0
              107        31007.0
              108        31008.0
              109        41101.0
              110        41102.0
              111        41103.0
              112        41104.0
              113        41105.0
              114        41106.0
              115        41107.0
              116        41108.0
              117        41110.0
              118        41111.0
              119        41112.0
              120        41114.0
              121        41116.0
              122        41119.0
              123        41120.0
              124        41121.0
              125        41122.0
              126        41123.0
              127        41125.0
              128        41126.0
              129        41127.0
              130        41128.0
              131        41129.0
              132        41130.0
              133        41131.0
              134        41132.0
              135        41133.0
              136        41134.0
              137        41135.0
              138        41136.0
              139        41137.0
              140        41138.0
              141        41140.0
              142        41141.0
              143        41142.0
              144        41143.0
              145        41144.0
              146        41145.0
              147        41146.0
              148        41147.0
              149        41148.0
              150        41149.0
              151        41150.0
              152        41151.0
              153        41201.0
              154        41202.0
              155        41203.0
              156        41204.0
              157        41205.0
              158        41206.0
              159        41207.0
              160        41208.0
              161        41209.0
              162        41210.0
              163        41211.0
              164        41212.0
              165        41213.0
              166        41214.0
              167        41215.0
              168        41216.0
              169        41217.0
              170        41301.0
              171        41302.0
              172        41303.0
              173        41304.0
              174        41305.0
              175        41306.0
              176        41307.0
              177        41308.0
              178        41309.0
              179        41310.0
              180        41312.0
              181        41313.0
              182        41314.0
              183        41315.0
              184        41316.0
              185        41317.0
              186        41318.0
              187        41319.0
              188        41320.0
              189        41321.0
              190        41401.0
              191        41402.0
              192        41403.0
              193        41501.0
              194        41502.0
              195        41503.0
              196        41601.0
              197        41701.0
              198        41702.0
              199        42001.0
              200        42003.0
              201        42004.0
              202        43001.0
              203        43002.0
              204        43003.0
              205        43004.0
              206        43005.0
              207        43006.0
              208        43007.0
              209        44001.0
              210        44002.0
              211        44003.0
              212        44004.0
              213        44005.0
              214        44006.0
              215        44007.0
              216        44008.0
              217        45001.0
              218        45002.0
              219        45003.0
              220        46002.0
              221        46003.0
              222        46004.0
              223        46005.0
              224        46006.0
              225        46007.0
              226        46008.0
              227        46009.0
              228        46012.0
              229        46013.0
              230        46015.0
              231        46016.0
              232        46017.0
              233        46018.0
              234        46019.0
              235        46020.0
              236        46021.0
              237        46022.0
              238        46023.0
              239        46024.0
              240        46025.0
              241        46026.0
              242        46027.0
              243        46028.0
              244        47001.0
              245        47002.0
              246        47003.0
              247        47005.0
              248        47008.0
              249        47009.0
              250        47010.0
              251        47011.0
              252        47012.0
              253        47013.0
              254        47015.0
              255        47017.0
              256        47018.0
              257        47019.0
              258        47020.0
              259        47021.0
              260        47022.0
              261        47025.0
              262        47026.0
              263        47027.0
              264        47028.0
              265        47029.0
              266        47034.0
              267        47035.0
              268        47036.0
              269        47037.0
              270        47040.0
              271        47041.0
              272        47042.0
              273        47043.0
              274        47044.0
              275        47045.0
              276        47046.0
              277        47047.0
              278        47050.0
              279        47051.0
              280        47053.0
              281        47054.0
              282        47055.0
              283        47056.0
              284        47057.0
              285        47058.0
              286        47059.0
              287        47061.0
              288        47062.0
              289        47063.0
              290        47064.0
              291        47065.0
              292        47066.0
              293        47067.0
              294        47068.0
              295        47069.0
              296        47070.0
              297        47071.0
              298        47073.0
              299        47074.0
              300        47075.0
              301        47076.0
              302        47077.0
              303        47078.0
              304        47079.0
              305        47080.0
              306        47081.0
              307        47082.0
              308        47083.0
              309        47084.0
              310        47086.0
              311        47087.0
              312        47089.0
              313        47092.0
              314        47093.0
              315        47095.0
              316        47096.0
              317        47097.0
              318        47098.0
              319        47099.0
              320        47100.0
              321        47101.0
              322        47103.0
              323        47104.0
              324        47105.0
              325        47106.0
              326        47107.0
              327        47109.0
              328        47110.0
              329        47111.0
              330        47112.0
              331        47113.0
              332        47114.0
              333        47116.0
              334        47117.0
              335        47118.0
              336        47119.0
              337        47120.0
              338        47121.0
              339        47122.0
              340        47123.0
              341        47124.0
              342        47125.0
              343        47127.0
              344        47128.0
              345        47129.0
              346        47130.0
              347        47131.0
              348        47132.0
              349        47134.0
              350        47135.0
              351        47136.0
              352        47137.0
              353        47138.0
              354        47139.0
              355        47140.0
              356        47141.0
              357        47142.0
              358        47143.0
              359        47144.0
              360        47145.0
              361        47146.0
              362        47147.0
              363        47148.0
              364        47149.0
              365        47150.0
              366        47400.0
              367        47501.0
              368        47502.0
              369        47503.0
              370        47504.0
              371        47701.0
              372        47702.0
              373        47703.0
              374        47704.0
              375        47705.0
              376        51001.0
              377        61001.0
              378        61003.0
              379        61004.0
              380        61005.0
              381        61006.0
              382        61007.0
              383        61008.0
              384        61009.0
              385        61010.0
              386        62001.0
              387        62002.0
              388        62003.0
              389        62004.0
              390        62005.0
              391        62006.0
              392        62007.0
              393        62008.0
              394        62009.0
              395        62010.0
              396        63001.0
              397        63002.0
              398        63003.0
              399        63004.0
              400        63005.0
              401        63006.0
              402        63007.0
              403        63008.0
              404        63009.0
              405        63010.0
              406        11000.0
              407        12000.0
              408        21000.0
              409        47000.0

In [58]:
list(df_lookup["recipients_list"]["recipients_list"])

[55.0,
 57.0,
 63.0,
 64.0,
 65.0,
 66.0,
 71.0,
 85.0,
 86.0,
 93.0,
 130.0,
 133.0,
 136.0,
 139.0,
 142.0,
 218.0,
 225.0,
 227.0,
 228.0,
 229.0,
 230.0,
 231.0,
 232.0,
 233.0,
 234.0,
 235.0,
 236.0,
 238.0,
 239.0,
 240.0,
 241.0,
 243.0,
 244.0,
 245.0,
 247.0,
 248.0,
 249.0,
 251.0,
 252.0,
 253.0,
 255.0,
 256.0,
 257.0,
 259.0,
 260.0,
 261.0,
 265.0,
 266.0,
 268.0,
 269.0,
 271.0,
 272.0,
 273.0,
 274.0,
 275.0,
 276.0,
 278.0,
 279.0,
 280.0,
 282.0,
 283.0,
 285.0,
 287.0,
 288.0,
 336.0,
 338.0,
 340.0,
 342.0,
 347.0,
 349.0,
 351.0,
 352.0,
 354.0,
 358.0,
 364.0,
 366.0,
 378.0,
 381.0,
 383.0,
 384.0,
 385.0,
 425.0,
 428.0,
 431.0,
 437.0,
 440.0,
 446.0,
 451.0,
 454.0,
 457.0,
 463.0,
 540.0,
 543.0,
 549.0,
 550.0,
 555.0,
 573.0,
 580.0,
 610.0,
 611.0,
 612.0,
 613.0,
 614.0,
 615.0,
 616.0,
 617.0,
 625.0,
 630.0,
 635.0,
 640.0,
 645.0,
 655.0,
 660.0,
 665.0,
 666.0,
 728.0,
 730.0,
 738.0,
 740.0,
 745.0,
 751.0,
 753.0,
 755.0,
 764.0,
 765.0,
 769.0,
 832.0,
 836.0,
 845.0,
 854.0,
 856.0,
 859.0,
 860.0,
 861.0,
 862.0,
 866.0,
 868.0,
 870.0,
 872.0,
 876.0,
 880.0,
 89.0,
 189.0,
 237.0,
 289.0,
 298.0,
 389.0,
 489.0,
 498.0,
 589.0,
 619.0,
 650.0,
 679.0,
 689.0,
 752.0,
 789.0,
 798.0,
 889.0,
 998.0,
 1027.0,
 1028.0,
 1029.0,
 1030.0,
 1031.0,
 1032.0,
 1033.0,
 1034.0,
 1035.0,
 3000.0]

In [ ]:
#recipients_list=df_recipients_list["RecipientCode"].to_list()

In [ ]:
#df_regional_recipients_list.head()

In [ ]:
#df_filter_regional=df_regional_recipients_list[df_regional_recipients_list.GroupID==15006]
#regional_recipients_list=df_filter_regional["RecipientCode"].to_list()

In [ ]:
#regional_recipients_list

In [ ]:
#len(recipients_list+regional_recipients_list),len(recipients_list),len(regional_recipients_list)

(168, 141, 27)

In [59]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [ ]:

df.head()  # Display the first few rows of the DataFrame

   RecipientCode          RecipientNameE  GroupID
0             55                 Türkiye    10019
1             57                  Kosovo    10019
2             63                  Serbia    10019
3             64  Bosnia and Herzegovina    10019
4             65              Montenegro    10019

#### errormessage : Recipient code not on DAC list of recipients

In [60]:
# import recipients_list
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            ((~df["Recipient code"].isin(list(df_lookup["recipients_list"]["recipients_list"]))))]

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element,error_message,warning_message
17,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,1,African Development Bank,12004.0,NaN,10,420,H06,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,

In [61]:
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            ((~df["Recipient code"].isin(list(df_lookup["recipients_list"]["recipients_list"])))), "error_message"] = df["error_message"] + " ;Recipient code not on DAC list of recipients"

In [62]:
df[["Type of flow (main DAC 1 category)","Recipient code", "error_message"]].head(20)

    Type of flow (main DAC 1 category)  Recipient code                                   error_message
0                                   10            3000
1                                   10             998
2                                   10             249
3                                   10             998
4                                   21             998
5                                   10             998
6                                   10             998
7                                   60             998
8                                   10             998
9                                   10             249
10                                  10             249
11                                  10            3000
12                                  10             998
13                                  10             998
14                                  10             998
15                                  10             998
16                                  10              85
17                                  10               1   ;Recipient code not on DAC list of recipients

#### errormessage : When recipient code = 3000, Bi/Multi should = 2

In [19]:
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            ((df["Recipient code"]== 3000) &
              (df["Bi/Multi"]!=2))]

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element,error_message,warning_message
11,2024,2022-01-15 00:00:00,1,1,20220000002,abcd,1,3000,International Committee of the Red Cross,21009.0,7,10,110,A01,Programme d'agriculture durable et de sécurité...,12240:100,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,

In [20]:
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            ((df["Recipient code"]== 3000) &
              (df["Bi/Multi"]!=2)), "error_message"] = df["error_message"] + "When recipient code = 3000, Bi/Multi should = 2"

In [21]:
df[["Type of flow (main DAC 1 category)","Recipient code", "Bi/Multi", "error_message"]].head(20)

    Type of flow (main DAC 1 category)  Recipient code  Bi/Multi                                    error_message
0                                   10            3000         2
1                                   10             998         2
2                                   10             249         8
3                                   10             998         4
4                                   21             998         8
5                                   10             998         3
6                                   10             998         3
7                                   60             998         7
8                                   10             998         2
9                                   10             249         7
10                                  10             249         7
11                                  10            3000         7  When recipient code = 3000, Bi/Multi should = 2
12                                  10             998         8
13                                  10             998         2
14                                  10             998         2

#### errormessage : In-donor refugee costs cannot be attributed to a specific recipient and therefore should be marked 998;

In [24]:
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            (df["Co-operation modality (replaces the type of aid)"].astype(str).str.startswith("H0")) & 
            (df["Co-operation modality (replaces the type of aid)"]!= "H01") &
              (df["Recipient code"]!= 998)]

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element,error_message,warning_message
17,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,85,African Development Bank,12004.0,1,10,420,H06,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,

In [25]:
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            (df["Co-operation modality (replaces the type of aid)"].astype(str).str.startswith("H0")) & 
            (df["Co-operation modality (replaces the type of aid)"]!= "H01") &
              (df["Recipient code"]!= 998), "error_message"] = df["error_message"] + " ;In-donor refugee costs cannot be attributed to a specific recipient and therefore should be marked 998; "

In [26]:
df[["Type of flow (main DAC 1 category)","Recipient code", "Bi/Multi","Co-operation modality (replaces the type of aid)", "error_message"]].head(20)

    Type of flow (main DAC 1 category)  Recipient code  Bi/Multi Co-operation modality (replaces the type of aid)                                      error_message
0                                   10            3000         2                                              NaN
1                                   10             998         2                                              NaN
2                                   10             249         8                                              A02
3                                   10             998         4                                              A02
4                                   21             998         8                                              NaN
5                                   10             998         3                                              B01
6                                   10             998         3                                              B01
7                                   60             998         7                                              NaN
8                                   10             998         2                                              B01
9                                   10             249         7                                              B01
10                                  10             249         7                                              A01
11                                  10            3000         7                                              A01
12                                  10             998         8                                              B02
13                                  10             998         2                                              B02
14                                  10             998         2                                              NaN
15                                  10             998         1                                              H02
16                                  10              85         1                                              H01
17                                  10              85         1                                              H06   ;In-donor refugee costs cannot be attributed ...

#### How to do a left join for parent channel code

In [ ]:
df_lookup.keys()

odict_keys(['annex2_lookup', 'channels_list', 'currency_list', 'donor_agency_lookup', 'donor_countries', 'finance_list', 'list_guarantees', 'long_channels_list', 'lookup_donor', 'multilateral_donors', 'parent_channel_lookup', 'private_donors', 'purposes_list', 'recipients_list', 'regional_recipients'])

In [67]:
df_lookup["parent_channel_lookup"]

     channel_code  parent_channel
0         11001.0         11000.0
1         11002.0         11000.0
2         11003.0         11000.0
3         11004.0         11000.0
4         12001.0         12000.0
5         12002.0         12000.0
6         12003.0         12000.0
7         12004.0         12000.0
8         21001.0         21000.0
9         21002.0         47000.0
10        21003.0         23000.0
11        21004.0         51000.0
12        21005.0         21000.0
13        21006.0         22000.0
14        21007.0         21000.0
15        21008.0         22000.0
16        21009.0         51000.0
17        21010.0         23000.0
18        21011.0         21000.0
19        21013.0         21000.0
20        21014.0         22000.0
21        21015.0         22000.0
22        21016.0         21000.0
23        21017.0         32000.0
24        21018.0         21000.0
25        21019.0         22000.0
26        21020.0         21000.0
27        21021.0         51000.0
28        21022.0         21000.0
29        21023.0         21000.0
30        21024.0         21000.0
31        21025.0         22000.0
32        21026.0         22000.0
33        21027.0         22000.0
34        21028.0         23000.0
35        21029.0         21000.0
36        21030.0         23000.0
37        21031.0         21000.0
38        21032.0         21000.0
39        21033.0         22000.0
40        21034.0         21000.0
41        21035.0         22000.0
42        21036.0         21000.0
43        21037.0         22000.0
44        21038.0         21000.0
45        21039.0         51000.0
46        21040.0         22000.0
47        21041.0         21000.0
48        21042.0         21000.0
49        21043.0         32000.0
50        21044.0         21000.0
51        21045.0         21000.0
52        21046.0         21000.0
53        21047.0         22000.0
54        21048.0         23000.0
55        21049.0         22000.0
56        21050.0         22000.0
57        21051.0         23000.0
58        21053.0         21000.0
59        21054.0         21000.0
60        21055.0         23000.0
61        21056.0         31000.0
62        21057.0         21000.0
63        21058.0         22000.0
64        21059.0         23000.0
65        21060.0         22000.0
66        21061.0         21000.0
67        21062.0         21000.0
68        21063.0         21000.0
69        21064.0         21000.0
70        21501.0         21000.0
71        21502.0         21000.0
72        21503.0         21000.0
73        21504.0         21000.0
74        21505.0         21000.0
75        21506.0         21000.0
76        21507.0         21000.0
77        21508.0         21000.0
78        21509.0         21000.0
79        22501.0         22000.0
80        22502.0         22000.0
81        23501.0         23000.0
82        30001.0         31000.0
83        30003.0         31000.0
84        30004.0         31000.0
85        30005.0         31000.0
86        30006.0         31000.0
87        30007.0         31000.0
88        30008.0         31000.0
89        30009.0         31000.0
90        30010.0         41100.0
91        30011.0         31000.0
92        30012.0         31000.0
93        30013.0         31000.0
94        30014.0         31000.0
95        30015.0         31000.0
96        30016.0         31000.0
97        30017.0         31000.0
98        30018.0         31000.0
99        30019.0         31000.0
100       30020.0         31000.0
101       31001.0         32000.0
102       31002.0         32000.0
103       31003.0         32000.0
104       31004.0         32000.0
105       31005.0         32000.0
106       31006.0         31000.0
107       31007.0         32000.0
108       31008.0         32000.0
109       41101.0         41100.0
110       41102.0         47000.0
111       41103.0         41100.0
112       41104.0         41300.0
113       41105.0         41300.0
114       41106.0         41300.0
115       41107.0         41100.0
116       41108.0         41100.0
117       41110.0         41100.0
118       41111.0         41100.0
119       41112.0         41100.0
120       41114.0         41100.0
121       41116.0         41100.0
122       41119.0         41100.0
123       41120.0         41100.0
124       41121.0         41100.0
125       41122.0         41100.0
126       41123.0         41100.0
127       41125.0         41100.0
128       41126.0         41600.0
129       41127.0         41100.0
130       41128.0         41300.0
131       41129.0         41100.0
132       41130.0         41100.0
133       41131.0         41100.0
134       41132.0         41600.0
135       41133.0         41600.0
136       41134.0         41100.0
137       41135.0         41100.0
138       41136.0         41600.0
139       41137.0         41600.0
140       41138.0         41600.0
141       41140.0         41100.0
142       41141.0         41400.0
143       41142.0         41600.0
144       41143.0         41100.0
145       41144.0         41100.0
146       41145.0         41100.0
147       41146.0         41100.0
148       41147.0         41400.0
149       41148.0         41500.0
150       41149.0         41100.0
151       41150.0         41300.0
152       41151.0         41300.0
153       41201.0         41200.0
154       41202.0         41200.0
155       41203.0         41200.0
156       41204.0         41200.0
157       41205.0         41200.0
158       41206.0         41200.0
159       41207.0         41200.0
160       41208.0         41200.0
161       41209.0         41200.0
162       41210.0         41200.0
163       41211.0         41200.0
164       41212.0         41200.0
165       41213.0         41200.0
166       41214.0         41200.0
167       41215.0         41200.0
168       41216.0         41200.0
169       41217.0         41200.0
170       41301.0         41300.0
171       41302.0         41300.0
172       41303.0         41300.0
173       41304.0         41300.0
174       41305.0         41300.0
175       41306.0         41300.0
176       41307.0         41300.0
177       41308.0         41300.0
178       41309.0         41300.0
179       41310.0         41300.0
180       41312.0         41300.0
181       41313.0         41300.0
182       41314.0         41300.0
183       41315.0         41300.0
184       41316.0         41300.0
185       41317.0         47000.0
186       41318.0         41600.0
187       41319.0         41300.0
188       41320.0         41100.0
189       41321.0         41300.0
190       41401.0         41400.0
191       41402.0         41400.0
192       41403.0         41400.0
193       41501.0         41400.0
194       41502.0         41300.0
195       41503.0         41400.0
196       41601.0         41600.0
197       41701.0         41700.0
198       41702.0         41700.0
199       42001.0         42000.0
200       42003.0         42000.0
201       42004.0         42000.0
202       43001.0         43000.0
203       43002.0         43000.0
204       43003.0         43000.0
205       43004.0         43000.0
206       43005.0         43000.0
207       43006.0         43000.0
208       43007.0         43000.0
209       44001.0         44000.0
210       44002.0         44000.0
211       44003.0         44000.0
212       44004.0         44000.0
213       44005.0         44000.0
214       44006.0         44000.0
215       44007.0         44000.0
216       44008.0         44000.0
217       45001.0         41100.0
218       45002.0         41100.0
219       45003.0         41100.0
220       46002.0         46000.0
221       46003.0         46000.0
222       46004.0         46000.0
223       46005.0         46000.0
224       46006.0         46000.0
225       46007.0         46000.0
226       46008.0         46000.0
227       46009.0         46000.0
228       46012.0         46000.0
229       46013.0         46000.0
230       46015.0         46000.0
231       46016.0         46000.0
232       46017.0         46000.0
233       46018.0         46000.0
234       46019.0         46000.0
235       46020.0         46000.0
236       46021.0         46000.0
237       46022.0         46000.0
238       46023.0         46000.0
239       46024.0         46000.0
240       46025.0         46000.0
241       46026.0         46000.0
242       46027.0         46000.0
243       46028.0         46000.0
244       47001.0         47000.0
245       47002.0         47000.0
246       47003.0         47000.0
247       47005.0         47000.0
248       47008.0         51000.0
249       47009.0         47000.0
250       47010.0         32000.0
251       47011.0         47000.0
252       47012.0         47000.0
253       47013.0         47000.0
254       47015.0         47000.0
255       47017.0         51000.0
256       47018.0         51000.0
257       47019.0         47000.0
258       47020.0         51000.0
259       47021.0         51000.0
260       47022.0         47000.0
261       47025.0         47000.0
262       47026.0         47000.0
263       47027.0         47000.0
264       47028.0         32000.0
265       47029.0         47000.0
266       47034.0         47000.0
267       47035.0         21000.0
268       47036.0         47000.0
269       47037.0         47000.0
270       47040.0         47000.0
271       47041.0         51000.0
272       47042.0         22000.0
273       47043.0         31000.0
274       47044.0         47000.0
275       47045.0         47000.0
276       47046.0         47000.0
277       47047.0         51000.0
278       47050.0         47000.0
279       47051.0         51000.0
280       47053.0         51000.0
281       47054.0         51000.0
282       47055.0         51000.0
283       47056.0         51000.0
284       47057.0         51000.0
285       47058.0         47000.0
286       47059.0         47000.0
287       47061.0         47000.0
288       47062.0         51000.0
289       47063.0         51000.0
290       47064.0         47000.0
291       47065.0         41600.0
292       47066.0         41100.0
293       47067.0         47000.0
294       47068.0         47000.0
295       47069.0         51000.0
296       47070.0         51000.0
297       47071.0         51000.0
298       47073.0         47000.0
299       47074.0         47000.0
300       47075.0         51000.0
301       47076.0         47000.0
302       47077.0         47000.0
303       47078.0         41600.0
304       47079.0         47000.0
305       47080.0         47000.0
306       47081.0         47000.0
307       47082.0         47000.0
308       47083.0         41100.0
309       47084.0         47000.0
310       47086.0         47000.0
311       47087.0         47000.0
312       47089.0         47000.0
313       47092.0         47000.0
314       47093.0         47000.0
315       47095.0         47000.0
316       47096.0         47000.0
317       47097.0         47000.0
318       47098.0         47000.0
319       47099.0         51000.0
320       47100.0         47000.0
321       47101.0         51000.0
322       47103.0         51000.0
323       47104.0         51000.0
324       47105.0         47000.0
325       47106.0         47000.0
326       47107.0         47000.0
327       47109.0         47000.0
328       47110.0         47000.0
329       47111.0         47000.0
330       47112.0         47000.0
331       47113.0         47000.0
332       47114.0         47000.0
333       47116.0         47000.0
334       47117.0         47000.0
335       47118.0         47000.0
336       47119.0         47000.0
337       47120.0         47000.0
338       47121.0         47000.0
339       47122.0         47000.0
340       47123.0         47000.0
341       47124.0         47000.0
342       47125.0         47000.0
343       47127.0         47000.0
344       47128.0         47000.0
345       47129.0         47000.0
346       47130.0         47000.0
347       47131.0         47000.0
348       47132.0         47000.0
349       47134.0         47000.0
350       47135.0         47000.0
351       47136.0         47000.0
352       47137.0         47000.0
353       47138.0         47000.0
354       47139.0         47000.0
355       47140.0         47000.0
356       47141.0         47000.0
357       47142.0         47000.0
358       47143.0         47000.0
359       47144.0         47000.0
360       47145.0         47000.0
361       47146.0         47000.0
362       47147.0         47000.0
363       47148.0         47000.0
364       47149.0         47000.0
365       47150.0         47000.0
366       47400.0         47000.0
367       47501.0         47000.0
368       47502.0         47000.0
369       47503.0         47000.0
370       47504.0         47000.0
371       47701.0         47000.0
372       47702.0         47000.0
373       47703.0         47000.0
374       47704.0         47000.0
375       47705.0         47000.0
376       51001.0         51000.0
377       61001.0         61000.0
378       61003.0         61000.0
379       61004.0         61000.0
380       61005.0         61000.0
381       61006.0         61000.0
382       61007.0         61000.0
383       61008.0         61000.0
384       61009.0         61000.0
385       61010.0         61000.0
386       62001.0         62000.0
387       62002.0         62000.0
388       62003.0         62000.0
389       62004.0         62000.0
390       62005.0         62000.0
391       62006.0         62000.0
392       62007.0         62000.0
393       62008.0         62000.0
394       62009.0         62000.0
395       62010.0         62000.0
396       63001.0         63000.0
397       63002.0         63000.0
398       63003.0         63000.0
399       63004.0         63000.0
400       63005.0         63000.0
401       63006.0         63000.0
402       63007.0         63000.0
403       63008.0         63000.0
404       63009.0         63000.0
405       63010.0         63000.0
406       11000.0         11000.0
407       12000.0         12000.0
408       21000.0         21000.0
409       47000.0         47000.0
410       23000.0         23000.0
411       51000.0         51000.0
412       22000.0         22000.0
413       32000.0         32000.0
414       31000.0         31000.0
415       41100.0         41100.0
416       41300.0         41300.0
417       41600.0         41600.0
418       41400.0         41400.0
419       41500.0         41500.0
420       41200.0         41200.0
421       41700.0         41700.0
422       42000.0         42000.0
423       43000.0         43000.0
424       44000.0         44000.0
425       46000.0         46000.0
426       61000.0         61000.0
427       62000.0         62000.0
428       63000.0         63000.0
429       10000.0         10000.0
430       13000.0         13000.0
431       20000.0         20000.0
432       30000.0         30000.0
433       40000.0         40000.0
434       41000.0         41000.0
435       50000.0         50000.0
436       60000.0         60000.0
437       90000.0         90000.0

In [68]:
pd.merge(left=df,right=df_lookup["parent_channel_lookup"],how="left",left_on="Channel code",right_on="channel_code")

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element,error_message,warning_message,channel_code,parent_channel
0,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,3000,African Development Bank,12004.0,2.0,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,12004.0,12000.0
1,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,2.0,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,12004.0,12000.0
2,2024,2024-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,NaN,8.0,10,110,A02,Programme d'agriculture durable et de sécurité...,99810,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN
3,2024,2021-12-31 00:00:00,1,1,20220000003,abcd,3,998,Institute for Advanced Research and Policy Stu...,51010.0,4.0,10,110,A02,Education for All: Inclusive Learning Environm...,42559;12264,"Himalayan Mountain Range, Nepal",NaN,NaN,NaN,The objective of this project is to ensure acc...,5.a;5.b,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0,2,302,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN
4,2024,2024-01-01 00:00:00,1,1,20220000004,abcd,1,998,Republic of Ireland,12003.0,8.0,21,420,NaN,Clean Water and Sanitation for Communities,41000,"Great Rift Valley, Kenya",NaN,NaN,NaN,This project aims to provide clean and safe dr...,5,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2,820,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,12003.0,12000.0
5,2024,2024-01-01 00:00:00,7000,1,20220000005,abcd,8,998,Private sector partnership with local small an...,21045.0,3.0,10,110,B01,Renewable Energy for Sustainable Development,23231,NaN,NaN,NaN,NaN,This project focuses on increasing access to r...,NaN,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,62,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,21045.0,21000.0
6,2024,2024-01-01 00:00:00,1,1,20220000005,abcd,8,998,Private sector partnership with local small an...,NaN,3.0,10,110,B01,Vedvarende energi til bæredygtig udvikling,45866,"Ganges River Delta, Bangladesh",4.0,NaN,NaN,This project focuses on increasing access to r...,1;2;3;4;5;6;7;8;9;10;11,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,62,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,NaN
7,2024,NaN,1,1,20220000002,abcd,1,998,International Committee of the Red Cross,47035.0,7.0,60,600,NaN,Este proyecto pretende promover prácticas agrí...,43060,NaN,NaN,NaN,NaN,This project seeks to promote sustainable agri...,NaN,NaN,2,2.0,2.0,2.0,0.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,47035.0,21000.0
8,2024,2023-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,30015.0,2.0,10,420,B01,Rural Healthcare Enhancement Initiative,51010:19.5|45866:30|51010:50.5,NaN,NaN,NaN,NaN,The initiative will focus on maternal and chil...,13,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,30015.0,31000.0
9,2024,2022-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,21009.0,7.0,10,110,B01,Programme d'agriculture durable et de sécurité...,12240,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,21009.0,51000.0
10,2024,2022-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,21009.0,7.0,10,110,A01,Programme d'agriculture durable et de sécurité...,12240:100,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,21009.0,51000.0
11,2024,2022-01-15 00:00:00,1,1,20220000002,abcd,1,3000,International Committee of the Red Cross,21009.0,7.0,10,110,A01,Programme d'agriculture durable et de sécurité...,12240:100,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,21009.0,51000.0
12,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,8.0,10,420,B02,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,12004.0,12000.0
13,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,2.0,10,420,B02,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,12004.0,12000.0
14,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,2.0,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,12004.0,12000.0
15,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,9.0,10,420,H02,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,12004.0,12000.0
16,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,85,African Development Bank,12004.0,1.0,10,420,H01,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,12004.0,12000.0
17,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,1,African Development Bank,12004.0,NaN,10,420,H06,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,;Recipient code not on DAC list of recipients,,12004.0,12000.0