## Catch-up Python training session - August 20th - Aid_t

In [77]:
import pandas as pd

In [78]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [79]:
df = pd.read_excel(r"\\main.oecd.org\ASgenDCD\DEVELOPMENT_AID\__PROCESSING\checklist_r\2_functions\test_crstemplate_GG.xlsx",header = 1)
df = df.loc[1:].reset_index(drop=True)

In [80]:
df.head()

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element
0,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,2,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,2024-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,NaN,8,10,110,A02,Programme d'agriculture durable et de sécurité...,99810,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,2021-12-31 00:00:00,1,1,20220000003,abcd,3,998,Institute for Advanced Research and Policy Stu...,51010.0,4,10,110,A02,Education for All: Inclusive Learning Environm...,42559;12264,"Himalayan Mountain Range, Nepal",NaN,NaN,NaN,The objective of this project is to ensure acc...,5.a;5.b,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0,2,302,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,2024-01-01 00:00:00,1,1,20220000004,abcd,1,998,Republic of Ireland,12003.0,8,21,420,NaN,Clean Water and Sanitation for Communities,41000,"Great Rift Valley, Kenya",NaN,NaN,NaN,This project aims to provide clean and safe dr...,5,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2,820,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,2024-01-01 00:00:00,7000,1,20220000005,abcd,8,998,Private sector partnership with local small an...,21045.0,3,10,110,B01,Renewable Energy for Sustainable Development,23231,NaN,NaN,NaN,NaN,This project focuses on increasing access to r...,NaN,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,62,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
for i,  row in df.iterrows():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11

In [96]:
df["errormessage"]= "" #Initialize the error message column
df["warningmessage"]= "" #Initialize the error message column

for i, row in df.iterrows():
    if ( row["Type of flow (main DAC 1 category)"]==10 or row["Type of flow (main DAC 1 category)"]==21 or row["Type of flow (main DAC 1 category)"]==60 ) & (pd.isna(row["Co-operation modality (replaces the type of aid)"])):
        df.loc[i,"errormessage"]= df.loc[i,"errormessage"]+"; ""Co-operation modality (replaces the type of aid) is missing for this type of flow"
        
    if ( row["Type of flow (main DAC 1 category)"]==10 or row["Type of flow (main DAC 1 category)"]==21 or row["Type of flow (main DAC 1 category)"]==60 ) & (row["Co-operation modality (replaces the type of aid)"]=="A01"):
        df.loc[i,"errormessage"]= df.loc[i,"warningmessage"]+"; ""Purpose code should be 51010 when co-operation modality is A01"

In [97]:
df["Co-operation modality (replaces the type of aid)"].isna().sum() # Count of missing values in the specified column

3

In [98]:
df[["Type of flow (main DAC 1 category)","Co-operation modality (replaces the type of aid)","errormessage","warningmessage"]].head()

   Type of flow (main DAC 1 category) Co-operation modality (replaces the type of aid)                                       errormessage warningmessage
0                                  10                                              NaN  ; Co-operation modality (replaces the type of ...
1                                  10                                              A02
2                                  10                                              A02
3                                  21                                              NaN  ; Co-operation modality (replaces the type of ...
4                                  10                                              B01

In [99]:
df.loc[3,"errormessage"]

'; Co-operation modality (replaces the type of aid) is missing for this type of flow'

In [100]:
example_test='OECD'

In [101]:
example_test[:2]

'OE'

In [102]:
df["Channel code"].astype(str)

0     12004.0
1         nan
2     51010.0
3     12003.0
4     21045.0
5         nan
6     47035.0
7     30015.0
8     21009.0
9     21009.0
10    21009.0
11    12004.0
Name: Channel code, dtype: object

In [103]:
df.loc[0,"Channel code"].astype(str)[:2]

'12'

In [104]:
df[["Channel code","Co-operation modality (replaces the type of aid)"]].head(20)

    Channel code Co-operation modality (replaces the type of aid)
0        12004.0                                              NaN
1            NaN                                              A02
2        51010.0                                              A02
3        12003.0                                              NaN
4        21045.0                                              B01
5            NaN                                              B01
6        47035.0                                              NaN
7        30015.0                                              B01
8        21009.0                                              B01
9        21009.0                                              A01
10       21009.0                                              A01
11       12004.0                                              A01

In [105]:
#Debugging
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            (df["Co-operation modality (replaces the type of aid)"]== "A01") &
              (~df["Channel code"].astype(str).str.startswith("12"))]

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element,errormessage,warningmessage,error_message
9,2024,2022-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,21009.0,7,10,110,A01,Programme d'agriculture durable et de sécurité...,12240:100,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,; Purpose code should be 51010 when co-operati...,,Parent channel should be 12000 when the Co-ope...
10,2024,2022-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,21009.0,7,10,110,A01,Programme d'agriculture durable et de sécurité...,12240:100,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,; Purpose code should be 51010 when co-operati...,,Parent channel should be 12000 when the Co-ope...

In [107]:
#Function
df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            (df["Co-operation modality (replaces the type of aid)"]== "A01") &
              (~df["Channel code"].astype(str).str.startswith("12")), "error_message"] += "Parent channel should be 12000 when the Co-operation modality is A01"

In [108]:
df[["Type of flow (main DAC 1 category)","Co-operation modality (replaces the type of aid)","Channel code","error_message"]].head(20)

    Type of flow (main DAC 1 category) Co-operation modality (replaces the type of aid)  Channel code                                      error_message
0                                   10                                              NaN       12004.0                                                NaN
1                                   10                                              A02           NaN                                                NaN
2                                   10                                              A02       51010.0                                                NaN
3                                   21                                              NaN       12003.0                                                NaN
4                                   10                                              B01       21045.0                                                NaN
5                                   10                                              B01           NaN                                                NaN
6                                   60                                              NaN       47035.0                                                NaN
7                                   10                                              B01       30015.0                                                NaN
8                                   10                                              B01       21009.0                                                NaN
9                                   10                                              A01       21009.0  Parent channel should be 12000 when the Co-ope...
10                                  10                                              A01       21009.0  Parent channel should be 12000 when the Co-ope...
11                                  10                                              A01       12004.0                                                NaN

In [109]:

df.loc[((df["Type of flow (main DAC 1 category)"]== 10) |
        (df["Type of flow (main DAC 1 category)"]== 21 ) | 
          (df["Type of flow (main DAC 1 category)"]== 60 )) &
            (df["Co-operation modality (replaces the type of aid)"]== "A02") &
              ((df["Sector / Purpose code and corresponding shares"].astype(str).str.contains("51010", na=False)) | 
                (df["Sector / Purpose code and corresponding shares"].astype(str).str.contains("51010:100", na=False))|
                (df["Sector / Purpose code and corresponding shares"].astype(str).str.contains("99810", na=False)) | 
                (df["Sector / Purpose code and corresponding shares"].astype(str).str.contains("99810:100", na=False))
                ), "error_message"] = df["error_message"] + "Purpose code should be different from 51010 or 99810 when the Co-operation modality is A01"

In [110]:
df[["Type of flow (main DAC 1 category)","Co-operation modality (replaces the type of aid)","Sector / Purpose code and corresponding shares","error_message"]].head(20)

    Type of flow (main DAC 1 category) Co-operation modality (replaces the type of aid) Sector / Purpose code and corresponding shares                                      error_message
0                                   10                                              NaN                  51010:20.12|45866:30|99810:40                                                NaN
1                                   10                                              A02                                          99810                                                NaN
2                                   10                                              A02                                    42559;12264                                                NaN
3                                   21                                              NaN                                          41000                                                NaN
4                                   10                                              B01                                          23231                                                NaN
5                                   10                                              B01                                          45866                                                NaN
6                                   60                                              NaN                                          43060                                                NaN
7                                   10                                              B01                 51010:19.5|45866:30|51010:50.5                                                NaN
8                                   10                                              B01                                          12240                                                NaN
9                                   10                                              A01                                      12240:100  Parent channel should be 12000 when the Co-ope...
10                                  10                                              A01                                      12240:100  Parent channel should be 12000 when the Co-ope...
11                                  10                                              A01                  51010:20.12|45866:30|99810:40                                                NaN